added libgsm to configure added CArchiver

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1258,6 +1258,7 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-sndfile-dir=PATH path to libsndfile installation
   --with-parapin-dir=PATH path to libparapin installation
+  --with-gsm-dir=PATH     path to libgsm installation
 
 Some influential environment variables:
   CC          C compiler command
@@ -4351,6 +4352,18 @@ if test "${with_parapin_dir+set}" = set; then
 fi
 
 
+# Check whether --with-gsm-dir was given.
+if test "${with_gsm_dir+set}" = set; then
+  withval=$with_gsm_dir;
+    CXXFLAGS="$CXXFLAGS -I${withval}/include"
+    LDFLAGS="$LDFLAGS -L${withval}/lib"
+    if test -n "${need_dash_r}"; then
+	LDFLAGS="$LDFLAGS -R${withval}/lib"
+    fi
+
+fi
+
+
 
 
 { echo "$as_me:$LINENO: checking for sf_open in -lsndfile" >&5
@@ -4511,6 +4524,88 @@ else
     echo
     echo "Or you can specify libparapin installation directory this way:"
     echo "./configure --with-parapin-dir=PATH"
+    echo
+    exit
+
+fi
+
+
+{ echo "$as_me:$LINENO: checking for gsm_create in -lgsm" >&5
+echo $ECHO_N "checking for gsm_create in -lgsm... $ECHO_C" >&6; }
+if test "${ac_cv_lib_gsm_gsm_create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgsm  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char gsm_create ();
+int
+main ()
+{
+return gsm_create ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_gsm_gsm_create=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_gsm_gsm_create=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_gsm_gsm_create" >&5
+echo "${ECHO_T}$ac_cv_lib_gsm_gsm_create" >&6; }
+if test $ac_cv_lib_gsm_gsm_create = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBGSM 1
+_ACEOF
+
+  LIBS="-lgsm $LIBS"
+
+else
+
+    echo
+    echo "You need to have libgsm installed on your system!"
+    echo "You can download it from http://kbs.cs.tu-berlin.de/~jutta/toast.html"
+    echo
+    echo "Or you can specify libgsm installation directory this way:"
+    echo "./configure --with-gsm-dir=PATH"
     echo
     exit
 
