speech synthesis works now

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -1262,6 +1262,7 @@ Optional Packages:
   --with-ogg-dir=PATH     path to libogg installation
   --with-samplerate-dir=PATH
                           path to libsamplerate installation
+  --with-flite-dir=PATH   path to libflite installation
 
 Some influential environment variables:
   CC          C compiler command
@@ -4391,6 +4392,18 @@ if test "${with_samplerate_dir+set}" = set; then
 fi
 
 
+# Check whether --with-flite-dir was given.
+if test "${with_flite_dir+set}" = set; then
+  withval=$with_flite_dir;
+    CXXFLAGS="$CXXFLAGS -I${withval}/include"
+    LDFLAGS="$LDFLAGS -L${withval}/lib"
+    if test -n "${need_dash_r}"; then
+	LDFLAGS="$LDFLAGS -R${withval}/lib"
+    fi
+
+fi
+
+
 
 
 { echo "$as_me:$LINENO: checking for sf_open in -lsndfile" >&5
@@ -4795,7 +4808,7 @@ else
     echo "You need to have libsamplerate installed on your system!"
     echo "You can download it from http://www.mega-nerd.com/SRC/"
     echo
-    echo "Or you can specify libogg installation directory this way:"
+    echo "Or you can specify libsamplerate installation directory this way:"
     echo "./configure --with-samplerate-dir=PATH"
     echo
     exit
@@ -4803,6 +4816,88 @@ else
 fi
 
 
+{ echo "$as_me:$LINENO: checking for flite_init in -lflite" >&5
+echo $ECHO_N "checking for flite_init in -lflite... $ECHO_C" >&6; }
+if test "${ac_cv_lib_flite_flite_init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lflite  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char flite_init ();
+int
+main ()
+{
+return flite_init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_flite_flite_init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_flite_flite_init=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_flite_flite_init" >&5
+echo "${ECHO_T}$ac_cv_lib_flite_flite_init" >&6; }
+if test $ac_cv_lib_flite_flite_init = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBFLITE 1
+_ACEOF
+
+  LIBS="-lflite $LIBS"
+
+else
+
+    echo
+    echo "You need to have libflite installed on your system!"
+    echo "You can download it from http://www.speech.cs.cmu.edu/flite/"
+    echo
+    echo "Or you can specify libflite installation directory this way:"
+    echo "./configure --with-flite-dir=PATH"
+    echo
+    exit
+
+fi
+
+LIBS="-lflite_cmu_us_kal -lflite_usenglish -lflite_cmulex $LIBS"
 
 
 ac_config_files="$ac_config_files Makefile src/Makefile conf/Makefile"
